import { TypeOfValues } from '../typings/utilities';

export const FIELD_TYPE = {
  LABEL: 'LABEL',
  SINGLE_LINE_TEXT: 'SINGLE_LINE_TEXT',
  MULTIPLE_LINE_TEXT: 'MULTIPLE_LINE_TEXT',
  EDITOR: 'EDITOR',
  DECIMAL: 'DECIMAL',
  CALC: 'CALC',
  MULTIPLE_CHECK: 'MULTIPLE_CHECK',
  SINGLE_CHECK: 'SINGLE_CHECK',
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTIPLE_SELECT: 'MULTIPLE_SELECT',
  FILE: 'FILE',
  DATE: 'DATE',
  DATETIME: 'DATETIME',
  TIME: 'TIME',
  USER_SELECT: 'USER_SELECT',
  ORGANIZATION_SELECT: 'ORGANIZATION_SELECT',
  GROUP_SELECT: 'GROUP_SELECT',
  LINK: 'LINK',
  LOOKUP: 'LOOKUP',
  REFERENCE_TABLE: 'REFERENCE_TABLE',
  SPACER: 'SPACER',
  HR: 'HR',
  RECORD_ID: 'RECORD_ID',
  CREATOR: 'CREATOR',
  CREATED_AT: 'CREATED_AT',
  MODIFIER: 'MODIFIER',
  MODIFIED_AT: 'MODIFIED_AT',
  CATEGORY: 'CATEGORY',
  STATUS: 'STATUS',
  STATUS_ASSIGNEE: 'STATUS_ASSIGNEE',
  GROUP: 'GROUP',
  TABLE: 'TABLE',
  TABLE_PLACEHOLDER: 'TABLE_PLACEHOLDER'
} as const;

export type FieldType = TypeOfValues<typeof FIELD_TYPE>;
