# 対象のブランチで `markdownlint --fix` を実行して結果をコミットする
name: fix markdown

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fix:
    if: ${{ !contains(github.ref_name, 'main') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'
      - run: npm ci
      - run: npm run markdownlint --fix 'src/**/*.md[x]'
        continue-on-error: true
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - run: |
          echo 自動での修正はありません
        if: steps.diff.outcome == 'success'
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m 'markdownlint --fix'
          git push
        if: steps.diff.outcome == 'failure'
